/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MathQuizV5;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Milu
 */
public class StartupScreen extends javax.swing.JFrame {

    /**
     * Creates new form StartupScreen
     */
    public StartupScreen() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        passwordsLbl = new javax.swing.JLabel();
        userNameLbl = new javax.swing.JLabel();
        SignupButton = new javax.swing.JButton();
        loginLbl = new javax.swing.JLabel();
        userPasswordField = new javax.swing.JPasswordField();
        userUsernameField = new javax.swing.JTextField();
        SignInButton = new javax.swing.JButton();
        logoLbl = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        menuLbl = new javax.swing.JLabel();
        playBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        highScoreBtn = new javax.swing.JButton();
        registerPanel = new javax.swing.JPanel();
        createAccLbl = new javax.swing.JLabel();
        cUserNameLbl = new javax.swing.JLabel();
        cPasswordLbl = new javax.swing.JLabel();
        cUserField = new javax.swing.JTextField();
        cAccountBtn = new javax.swing.JButton();
        cPasswordField = new javax.swing.JPasswordField();
        gameModePanel = new javax.swing.JPanel();
        gameModeLbl = new javax.swing.JLabel();
        scienceBtn = new javax.swing.JButton();
        bToMenuBtn = new javax.swing.JButton();
        mathBtn = new javax.swing.JButton();
        gameInfoPanel = new javax.swing.JPanel();
        startBtn = new javax.swing.JButton();
        infoTextArea = new javax.swing.JScrollPane();
        gameInfoTxtArea = new javax.swing.JTextArea();
        backBtn = new javax.swing.JButton();
        mathMode = new javax.swing.JPanel();
        QuestionLabel = new javax.swing.JLabel();
        QuestionNumberLbl = new javax.swing.JLabel();
        quitToMenuBtn = new javax.swing.JButton();
        nextMathQuestionBtn = new javax.swing.JButton();
        answerField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        passwordsLbl.setText("Password");

        userNameLbl.setText("Username");

        SignupButton.setText("Sign up");
        SignupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupButtonActionPerformed(evt);
            }
        });

        loginLbl.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        loginLbl.setText("Log in");

        SignInButton.setText("Sign in");
        SignInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInButtonActionPerformed(evt);
            }
        });

        logoLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        logoLbl.setText("Math Quiz V5");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(SignupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SignInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(353, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(loginLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(397, 397, 397))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(loginLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameLbl))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SignupButton)
                    .addComponent(SignInButton))
                .addGap(154, 154, 154))
        );

        getContentPane().add(loginPanel, "card10");

        menuLbl.setFont(new java.awt.Font("Fira Sans", 0, 36)); // NOI18N
        menuLbl.setText("Main Menu");

        playBtn.setText("Play");
        playBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        highScoreBtn.setText("High Scores");
        highScoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highScoreBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(menuLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(highScoreBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(playBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(383, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(menuLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(playBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(highScoreBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        getContentPane().add(menuPanel, "card3");

        createAccLbl.setFont(new java.awt.Font("Fira Sans", 0, 36)); // NOI18N
        createAccLbl.setText("Create an Account");

        cUserNameLbl.setText("Username");

        cPasswordLbl.setText("Password");

        cAccountBtn.setText("Create account");
        cAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cAccountBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                .addContainerGap(366, Short.MAX_VALUE)
                .addComponent(createAccLbl)
                .addGap(270, 270, 270))
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cPasswordLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cUserNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(cUserField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(createAccLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cUserNameLbl)
                    .addComponent(cUserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cPasswordLbl)
                    .addComponent(cPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(cAccountBtn)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        getContentPane().add(registerPanel, "card4");

        gameModeLbl.setFont(new java.awt.Font("Fira Sans", 0, 36)); // NOI18N
        gameModeLbl.setText("Choose game mode");

        scienceBtn.setText("Science");
        scienceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scienceBtnActionPerformed(evt);
            }
        });

        bToMenuBtn.setText("Back");
        bToMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bToMenuBtnActionPerformed(evt);
            }
        });

        mathBtn.setText("Math");
        mathBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gameModePanelLayout = new javax.swing.GroupLayout(gameModePanel);
        gameModePanel.setLayout(gameModePanelLayout);
        gameModePanelLayout.setHorizontalGroup(
            gameModePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameModePanelLayout.createSequentialGroup()
                .addContainerGap(305, Short.MAX_VALUE)
                .addGroup(gameModePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameModePanelLayout.createSequentialGroup()
                        .addComponent(gameModeLbl)
                        .addGap(300, 300, 300))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameModePanelLayout.createSequentialGroup()
                        .addGroup(gameModePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mathBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scienceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bToMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(410, 410, 410))))
        );
        gameModePanelLayout.setVerticalGroup(
            gameModePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameModePanelLayout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(gameModeLbl)
                .addGap(51, 51, 51)
                .addComponent(mathBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(scienceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(bToMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );

        getContentPane().add(gameModePanel, "card5");

        startBtn.setText("Start");

        gameInfoTxtArea.setColumns(20);
        gameInfoTxtArea.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        gameInfoTxtArea.setRows(5);
        gameInfoTxtArea.setText("In this game mode, you will be given randomized science related \nmath questions. You are given a limit of 10 minutes to answer as \nmany questions within the time frame. ");
        infoTextArea.setViewportView(gameInfoTxtArea);

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gameInfoPanelLayout = new javax.swing.GroupLayout(gameInfoPanel);
        gameInfoPanel.setLayout(gameInfoPanelLayout);
        gameInfoPanelLayout.setHorizontalGroup(
            gameInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameInfoPanelLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(gameInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameInfoPanelLayout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(430, 430, 430)
                        .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(infoTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
        );
        gameInfoPanelLayout.setVerticalGroup(
            gameInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameInfoPanelLayout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addComponent(infoTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(gameInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );

        getContentPane().add(gameInfoPanel, "card6");

        QuestionLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        QuestionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QuestionLabel.setText("(math question)");

        QuestionNumberLbl.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        QuestionNumberLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QuestionNumberLbl.setText("Question 1");

        quitToMenuBtn.setText("Quit quiz");
        quitToMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitToMenuBtnActionPerformed(evt);
            }
        });

        nextMathQuestionBtn.setText("Next question");

        javax.swing.GroupLayout mathModeLayout = new javax.swing.GroupLayout(mathMode);
        mathMode.setLayout(mathModeLayout);
        mathModeLayout.setHorizontalGroup(
            mathModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mathModeLayout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(quitToMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                .addComponent(nextMathQuestionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mathModeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mathModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mathModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mathModeLayout.createSequentialGroup()
                            .addComponent(QuestionNumberLbl)
                            .addGap(370, 370, 370))
                        .addGroup(mathModeLayout.createSequentialGroup()
                            .addComponent(QuestionLabel)
                            .addGap(329, 329, 329)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mathModeLayout.createSequentialGroup()
                        .addComponent(answerField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(384, 384, 384))))
        );
        mathModeLayout.setVerticalGroup(
            mathModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mathModeLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(QuestionNumberLbl)
                .addGap(44, 44, 44)
                .addComponent(QuestionLabel)
                .addGap(33, 33, 33)
                .addComponent(answerField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(mathModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quitToMenuBtn)
                    .addComponent(nextMathQuestionBtn))
                .addGap(116, 116, 116))
        );

        getContentPane().add(mathMode, "card7");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void SignInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInButtonActionPerformed
        String username = userUsernameField.getText();
        String password = new String(userPasswordField.getPassword());
        
        if(DbManager.checkUserInformation(username, password)) {
            loginPanel.setVisible(false);
            menuPanel.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Invalid username or password");
        }
    }//GEN-LAST:event_SignInButtonActionPerformed

    private void SignupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupButtonActionPerformed
        loginPanel.setVisible(false);
        registerPanel.setVisible(true);
    }//GEN-LAST:event_SignupButtonActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    
    //Create account screen
    private void cAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cAccountBtnActionPerformed
        String username = cUserField.getText();
        String password = new String(cPasswordField.getPassword());
        
        DbManager.registerUser(username, password);
        
        try {
            Thread.sleep(2000);
        } catch (InterruptedException ex) {
            Logger.getLogger(StartupScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        registerPanel.setVisible(false);
        loginPanel.setVisible(true);
    }//GEN-LAST:event_cAccountBtnActionPerformed

    private void highScoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highScoreBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_highScoreBtnActionPerformed

    private void playBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBtnActionPerformed
           menuPanel.setVisible(false);
           gameModePanel.setVisible(true);
    }//GEN-LAST:event_playBtnActionPerformed

    private void bToMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bToMenuBtnActionPerformed
        gameModePanel.setVisible(false);
        menuPanel.setVisible(true);
    }//GEN-LAST:event_bToMenuBtnActionPerformed

    private void scienceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scienceBtnActionPerformed
        gameModePanel.setVisible(false);
        gameInfoPanel.setVisible(true);
    }//GEN-LAST:event_scienceBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        gameInfoPanel.setVisible(false);
        gameModePanel.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void mathBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathBtnActionPerformed
        gameModePanel.setVisible(false);
        mathMode.setVisible(true);
        displayMathQuestion();
    }//GEN-LAST:event_mathBtnActionPerformed

    private void quitToMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitToMenuBtnActionPerformed
        mathMode.setVisible(false);
        gameModePanel.setVisible(true);
    }//GEN-LAST:event_quitToMenuBtnActionPerformed
    
    public void displayMathQuestion() {
        MathQuestions mathQuestions = new MathQuestions();
        QuestionLabel.setText(mathQuestions.getQuestionText());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel QuestionLabel;
    private javax.swing.JLabel QuestionNumberLbl;
    private javax.swing.JButton SignInButton;
    private javax.swing.JButton SignupButton;
    private javax.swing.JTextField answerField;
    private javax.swing.JButton bToMenuBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton cAccountBtn;
    private javax.swing.JPasswordField cPasswordField;
    private javax.swing.JLabel cPasswordLbl;
    private javax.swing.JTextField cUserField;
    private javax.swing.JLabel cUserNameLbl;
    private javax.swing.JLabel createAccLbl;
    private javax.swing.JButton exitBtn;
    private javax.swing.JPanel gameInfoPanel;
    private javax.swing.JTextArea gameInfoTxtArea;
    private javax.swing.JLabel gameModeLbl;
    private javax.swing.JPanel gameModePanel;
    private javax.swing.JButton highScoreBtn;
    private javax.swing.JScrollPane infoTextArea;
    private javax.swing.JLabel loginLbl;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel logoLbl;
    private javax.swing.JButton mathBtn;
    private javax.swing.JPanel mathMode;
    private javax.swing.JLabel menuLbl;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton nextMathQuestionBtn;
    private javax.swing.JLabel passwordsLbl;
    private javax.swing.JButton playBtn;
    private javax.swing.JButton quitToMenuBtn;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JButton scienceBtn;
    private javax.swing.JButton startBtn;
    private javax.swing.JLabel userNameLbl;
    private javax.swing.JPasswordField userPasswordField;
    private javax.swing.JTextField userUsernameField;
    // End of variables declaration//GEN-END:variables
}
